"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from inferra.src.models import tensorflow_model as tensorflow_model
from inferra.src.models import torch_model as torch_model
