"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from inferra.src.models import au57 as au57
from inferra.src.models import au57_test as au57_test
