"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from inferra.src.layers import tensorflow_layers as tensorflow_layers
from inferra.src.layers import torch_layers as torch_layers
